### ISSUE TITLE
Please include includes in the examples

### ISSUE THREAD

**Issue by BraindeadOne** [ocraft/ocraft-s2client#1]
Since the examples rely on static and/or ambiguous imports it's little fun to puzzle the required statements together.
It would be nice if you could either add them to the examples or include a link to a complete class below the extracts.

**Comment by ocraft** [comment]
You are right, the documentation is lacking right now. Actually there is a full code example: https://github.com/ocraft/ocraft-s2client/blob/master/ocraft-s2client-api/src/test/java/com/github/ocraft/s2client/api/OcraftS2ClientExamplesIT.java. I will try to polish documentation and add some links/sample project after I'll get more feedback from users. Currently I encourage you to look at the tests  (especially OcraftS2ClientEndToEndIT.java and OcraftS2ClientExamplesIT.java)  or ask me directly on discord channel (https://discordapp.com/channels/350289306763657218/381404462650097665).

**Comment by ocraft** [comment]
Ok, I improved documentation by adding required link and some description of basic step that should be done and where to start looking.
