### ISSUE TITLE
Connection timeout when rendering layer is active

### ISSUE THREAD

**Issue by boehmseb** [ocraft/ocraft-s2client#11]
When I activate the rendering layer, the ocraft client keeps waiting for responses to observation requests and ultimately the connection times out. This happens after a game has successfully been launched via S2Coordinator#launchGame().
I know for a fact, that the server receives and responds to the request (starcraft's console output + wireshark show that the data is actually sent). This does not happen when the rendering layer is not active. 
Again, I am working with the Linux Package, so it might be related to that (and therefore issue #9). Unfortunately, right now I cannot test this with the BattleNet version of StarCraft, but I might be able to do so in the coming days.

**Comment by ocraft** [comment]
Do you have similar problems with feature layers or it works correctly for you with linux package?

**Comment by boehmseb** [comment]
I have not tried that yet.

**Comment by boehmseb** [comment]
I quickly replaced `setRender` with `setFeatureLayers` and that worked just fine.

**Comment by boehmseb** [comment]
I did some more investigation and noticed that the most recent Linux package can only use protocol version 4.7.1 (ocraft actually warns about this but I managed to overlook that message). 
After I debugged myself through the different layers, I eventually discovered that the response is indeed received but the response parser never finishes its job, hanging in some kind loop.
So I would assume that the protocol mismatch is the issue and not a bug in ocraft. I guess I will have to wait until a new Linux package is published. Anyway, I think we can close this issue.

**Comment by boehmseb** [comment]
Unfortunately, there is still a bug with the rendering layer for which I did not find any documented change in the protocol definition:

I patched ocraft to use a protocol version I can work with (i.e. 4.7.1) and now observation responses can be parsed. However, an active rendering layer causes an exception because of the image format:
`java.lang.IllegalArgumentException: Unsupported image type with bits per pixel [24]. Expected {1, 8, 32}.`

**Comment by ocraft** [comment]
Fixed in version 0.3.2.
