### ISSUE TITLE
isPlacable and isPathable appear to be incorrect

### ISSUE THREAD

**Issue by ShadowLordAlpha** [ocraft/ocraft-s2client#17]
When attempting to get data from the isPathable and isPlaceable methods in the ObservationInterface the data returned appears to be incorrect. Not really sure how it would be incorrect but pulling the raw data and using a method I pulled out of the public code for Tyr I am getting the correct data with identical points.

**Comment by ocraft** [comment]
Are you sure that you using the newest version 0.3.10 and the most actual updates for the game?

**Comment by ShadowLordAlpha** [comment]
I should be as battlenet shows no updates for it and that is the library version i am using.

**Comment by ShadowLordAlpha** [comment]
Ocraft uses sc2api in version 4.10.3.76114. The game server uses 4.10.4.76811.
The library I have set to use is 0.3.10

I have attached an image of what the following code generates

`new Tile().location(Point.of(x, y, observation.terrainHeight(p2d)))
                        .buildable(observation.isPlacable(p2d))
                        .pathable(observation.isPathable(p2d))
                        .creep(observation.hasCreep(p2d));`

![wrong](https://user-images.githubusercontent.com/4204089/67835088-55a67c00-faa6-11e9-84c4-e3ff5151bcbc.png)


The debug method for that is 
`public void debug(DebugInterface debug) {

        for(Tile[] tileRow: tiles) {
            for(Tile tile: tileRow) {
                Color color = Color.RED;
                if(tile.buildable()) {
                    color = Color.GREEN;
                    if(tile.creep()) {
                        color = Color.PURPLE;
                    }
                } else if(tile.pathable()) {
                    color = Color.YELLOW;
                }

                //Point point = Point.of(tile.location().getX(), tile.location().getY(), height);
                Point point = Point.of(tile.location().getX(), tile.location().getY(), tile.location().getZ());
                debug.debugBoxOut(point, point.add(Point.of(1, 1, 1)), color);
            }
        }
    }`

So i would expect the ramps to basically be all yellow however as you can see the ramp is actually a mix of green (buildable) and Red (unknown) if you look the buildable area with creep is not all purple either. I don't believe i used the methods incorrectly but feel free to tell me if i did

**Comment by ocraft** [comment]
Could you provide me with a full sample code that will generate this tiles? This way it will be much easier to find solution for the problem.

**Comment by ShadowLordAlpha** [comment]
That is nearly it already by sure.

This is just a data class. I use lombak for it. if you don't or don't want to use it its just auto generated methods

`package com.shadowcs.sc2.empress.cartographer;

import com.github.ocraft.s2client.protocol.spatial.Point;
import lombok.Data;
import lombok.experimental.Accessors;

@Data
@Accessors(fluent=true)
public class Tile {

    private Point location;
    private boolean pathable;
    private boolean buildable;
    private boolean creep;
}
`

This is the class that creates the map
`package com.shadowcs.sc2.empress.cartographer;

import com.github.ocraft.s2client.bot.gateway.DebugInterface;
import com.github.ocraft.s2client.bot.gateway.ObservationInterface;
import com.github.ocraft.s2client.protocol.debug.Color;
import com.github.ocraft.s2client.protocol.game.raw.StartRaw;
import com.github.ocraft.s2client.protocol.response.ResponseGameInfo;
import com.github.ocraft.s2client.protocol.spatial.Point;
import com.github.ocraft.s2client.protocol.spatial.Point2d;
import com.github.ocraft.s2client.protocol.spatial.Size2dI;

public class CartographyQueen {

    private float height;
    private Tile[][] tiles;

    public CartographyQueen(ObservationInterface observation) {

        ResponseGameInfo gameInfo = observation.getGameInfo();
        StartRaw startRaw = gameInfo.getStartRaw().get();

        Size2dI size = startRaw.getMapSize();

        System.out.println(gameInfo.getMapName());
        System.out.println(startRaw.getMapSize());

        tiles = new Tile[size.getX()][size.getY()];

        for(int x = 0; x < size.getX(); x++) {
            for(int y = 0; y < size.getY(); y++) {
                Point2d p2d = Point2d.of(x, y);

                tiles[x][y] = new Tile().location(Point.of(x, y, observation.terrainHeight(p2d)))
                        .buildable(observation.isPlacable(p2d))
                        .pathable(observation.isPathable(p2d))
                        .creep(observation.hasCreep(p2d));
                if(height < observation.terrainHeight(p2d)) {
                    height = observation.terrainHeight(p2d);
                }
            }
        }
    }

    public void debug(DebugInterface debug) {

        for(Tile[] tileRow: tiles) {
            for(Tile tile: tileRow) {
                Color color = Color.RED;
                if(tile.buildable()) {
                    color = Color.GREEN;
                    if(tile.creep()) {
                        color = Color.PURPLE;
                    }
                } else if(tile.pathable()) {
                    color = Color.YELLOW;
                }

                //Point point = Point.of(tile.location().getX(), tile.location().getY(), height);
                Point point = Point.of(tile.location().getX(), tile.location().getY(), tile.location().getZ());
                debug.debugBoxOut(point, point.add(Point.of(1, 1, 1)), color);
            }
        }
    }
}
`

And to tie them together is just

`package com.shadowcs.sc2.empress;

import com.github.ocraft.s2client.bot.S2Agent;
import com.github.ocraft.s2client.bot.S2Coordinator;
import com.github.ocraft.s2client.bot.gateway.UnitInPool;
import com.github.ocraft.s2client.protocol.data.Abilities;
import com.github.ocraft.s2client.protocol.data.Units;
import com.github.ocraft.s2client.protocol.debug.Color;
import com.github.ocraft.s2client.protocol.game.BattlenetMap;
import com.github.ocraft.s2client.protocol.game.Difficulty;
import com.github.ocraft.s2client.protocol.game.Race;
import com.github.ocraft.s2client.protocol.spatial.Point;
import com.github.ocraft.s2client.protocol.unit.Unit;
import com.shadowcs.sc2.empress.core.Empress;

import java.util.List;
import java.util.Random;

public class Eva  extends S2Agent {

@Override
    public void onGameStart() {
CartographyQueen cartographyQueen = new CartographyQueen(observation());

        cartographyQueen.debug(debug());
        debug().debugGodMode();
        debug().sendDebug();
}
    public static void main(String...args) {

        Random random = new Random();
        Empress bot = new Empress();

        String map = bot.getSettings().getMapPool().get(random.nextInt(bot.getSettings().getMapPool().size()));

        S2Coordinator s2Coordinator = S2Coordinator.setup()
                .setRealtime(true)
                .loadSettings(args)
                .setParticipants(
                        S2Coordinator.createParticipant(bot.getSettings().getRace(), bot),
                        S2Coordinator.createComputer(Race.RANDOM, Difficulty.MEDIUM))
                .launchStarcraft()
                .startGame(BattlenetMap.of(map));

        while (s2Coordinator.update()) {
        }

        s2Coordinator.quit();
    }
}
`

**Comment by ocraft** [comment]
Problem should be fixed in ver. 0.3.11.

**Comment by ShadowLordAlpha** [comment]
Checked a few maps, everything looks good now!
