### ISSUE TITLE
Mac OS issue with versions directory

### ISSUE THREAD

**Issue by thefirebanks** [ocraft/ocraft-s2client#2]
Hello!

We are working on Mac OS, and when trying to run the "...ExamplesIT.java", we run into this issue

"java.lang.IllegalArgumentException: version directory is required"

 We think that it is because of the way paths are built on MacOS, because the executable path found in "ExecuteInfo.txt" is "/Applications/StarCraft II/Versions/Base60321/SC2.app/Contents/MacOS/SC2", but it is looking for the versions path in "/Applications/StarCraft II/Versions/Base60321/SC2.app/Versions", yet such folder does not exist there - and in fact we think it is looking for the "/Applications/StarCraft II/Versions/" instead. 

Is there a fix for this?

**Comment by ocraft** [comment]
Hi!

I will try to solve the problem with automatic executable path resolving on Mac OS, it looks like the game structure is different there. 

Right now you can start the game server manually and use only the client, i.e.
S2Client client = starcraft2Client().connectTo("127.0.01", 5000).start();

**Comment by ocraft** [comment]
Hi again!

I prepared fix to the problem, please try again and tell me if that worked for you.

**Comment by quinnbp** [comment]
@thefirebanks and I are working together. It appears that the posted fix resolves the issue, at least for the test files. Thanks!
