### ISSUE TITLE
Rich Vespian Refineries/Extractors/Assimilators don't have an entry in the Units enum

### ISSUE THREAD

**Issue by Ketroc** [ocraft/ocraft-s2client#20]
eg.  a refinery on a Rich Vespian Geyser has a Units.Other unit type and a unitTypeId of 1943... rather than being assigned to Units.TERRAN_REFINERY (or possibly a different entry like Units.TERRAN_REFINERY_RICH)

(WorldofSleepersLE.SC2Map is an example of a map with rich vespian geysers)

**Comment by ocraft** [comment]
Are you absolutely sure, that this id equals 1943 and it should be mapped to TERRAN_RAFINERY? I ask because 1943 is assigned to:
` {
            "id": 1943,
            "name": "MechaZerglingACGluescreenDummy"
  }` in the game.

**Comment by Ketroc** [comment]
It's mechzergling in patch 4.10.  The rich gas structures ids also changed between patch 4.10 and 4.11.  Here's the values:

4.11
REFINERY_RICH = 1943
ASSIMILATOR_RICH = 1956
EXTRACTOR_RICH = 1957

4.10
REFINERY_RICH = 1960
ASSIMILATOR_RICH = 1955
EXTRACTOR_RICH = 1956

**Comment by ocraft** [comment]
According to Blizzard, all ids are stable and immutable. I checked and in the newest path 4.11 nothing changed:

```
  {
            "id": 1955,
            "name": "AssimilatorRich"
        },
        {
            "id": 1956,
            "name": "ExtractorRich"
        },
        {
            "id": 1957,
            "name": "InhibitorZoneSmall"
        },
        {
            "id": 1958,
            "name": "InhibitorZoneMedium"
        },
        {
            "id": 1959,
            "name": "InhibitorZoneLarge"
        },
        {
            "id": 1960,
            "name": "RefineryRich"
        },
```

Can you verify these values in your  \Documents\StarCraft II\stableid.json  file? Do you know other people that have the same issue?

**Comment by ocraft** [comment]
Ok, I had old version of the file, you are right that these values are different right now.  Thats strange because Blizzard always assured that ids will never change, even the file with mappings is named "stableid".

**Comment by ocraft** [comment]
The easy solution in this situation is to make own type. You can do that with Units.from(1943). These enums are not necessary and are in the API only for convenience. I'm not sure yet how to provide an update for that situation because I want to provide API that will work on every version and many people use older Linux builds.

**Comment by Ketroc** [comment]
Seeing as the rich gas structures currently don't exist in ocraft at all, it wouldn't harm anything by adding it with the current patch's IDs.  It's not like you'd be changing any existing types.  Plus, as far as I'm aware, there is 4 bot authors using Java and none are using Linux.

I may not understand how Units.from works, but I don't think it will solve the issue.  Issue being that we can't reliably cast Unit.getType() to the Units enum without special handling for rich gas structures.

**Comment by ocraft** [comment]
Ocraft is used outside of the ladder, for example on universities for java learning courses, but you are right, adding this enum will not break anything.

**Comment by Ketroc** [comment]
Ya, I confirmed and the 4.10 ids are these ones:

4.10
rich refinery = 1960
rich assimilator = 1955
rich extractor = 1956
