### ISSUE TITLE
Debug.debugSphereOut() has swapped Red/Blue color channels

### ISSUE THREAD

**Issue by lpalm** [ocraft/ocraft-s2client#24]
DebugInterfaceImpl Line 116: If I want to get a Blue sphere, I have to send a Red Color and the other way around. It seems like the channels are swapped?

**Comment by ocraft** [comment]
```
debug().debugSphereOut(observation().getCameraPos(), 10.0f, Color.BLUE);
debug().sendDebug();
```
I've checked the code above on 4.11 path and the sphere is properly blue for me.

**Comment by lpalm** [comment]
I pasted your code and got a red sphere 
<img width="1146" alt="Screenshot 2020-05-05 at 9 36 15 PM" src="https://user-images.githubusercontent.com/8668240/81113667-86b1ae80-8f18-11ea-84f0-1b46bce2a5aa.png">


I'm running MacOS Catalina 10.15.4.
OCraft: Ocraft uses sc2api in version 4.10.3.76114. The game server uses 4.11.4.78285.
Starcraft v4.11.4

I'm guessing is a mac issue if you are not running mac.
https://stackoverflow.com/questions/228477/how-do-i-programmatically-determine-operating-system-in-java

 It might too much work to fix it, as its not a serious problem.

**Comment by lpalm** [comment]
I have Windows for bootcamp, so I installed SC2 and copied my bot to win. There have been no changes and a blue sphere was generated.

![Capture](https://user-images.githubusercontent.com/8668240/81173440-f61ab300-8f97-11ea-8b80-2b592b27025d.PNG)

I think the binary of SC2 for Mac is a little different than Windows, and the RBG is encoded as BGR. There's evidence on the internet of this. e.g. 
https://www.reddit.com/r/gamemaker/comments/9l58p7/hexa_color_code_inverted_mac_rgb_windows_bgr/
