### ISSUE TITLE
Request: Minimal example

### ISSUE THREAD

**Issue by Archiatrus** [ocraft/ocraft-s2client#3]
Hi,

Do you think it is possible to use your API to develop a bot that could compete in the Starcraft 2 AI Ladder?  The ladder calls a bot binary with [command line arguments](https://github.com/Cryptyc/CryptBot/blob/master/LadderInterface.h#L86) which tell the bot where it has to connect.

If it is possible, and if it is not too much effort, could you provide a minimal example? I would like to add it to the [wiki](http://wiki.sc2ai.net/Main_Page) so that people who would like to participate with java have a nice starting point.

Regards

**Comment by ocraft** [comment]
Hi, 

I added a minimal example of connection properties to documentation: https://github.com/ocraft/ocraft-s2client#minimal-configuration-example-of-command-line-connection-properties. I should release a new version to maven central today.
