### ISSUE TITLE
how can I cancel drawings.

### ISSUE THREAD

**Issue by K85** [ocraft/ocraft-s2client#49]
it's ok to use DebugDraw to draw graphics inside the game, while I can't find any function to erase or cancel the drawings before.

**Comment by ocraft** [comment]
<https://github.com/ocraft/ocraft-s2client/blob/397cab9b7a9e522be317213ed464125d7abd04d7/ocraft-s2client-bot/src/main/java/com/github/ocraft/s2client/bot/gateway/DebugInterface.java#L240> - sending a new set of debug commands clears the previous ones.

**Comment by K85** [comment]
> https://github.com/ocraft/ocraft-s2client/blob/397cab9b7a9e522be317213ed464125d7abd04d7/ocraft-s2client-bot/src/main/java/com/github/ocraft/s2client/bot/gateway/DebugInterface.java#L240
> 
> - sending a new set of debug commands clears the previous ones.

thanks, i am reading the javadoc currently.
the projeict is a great design.

**Comment by K85** [comment]
it seems i can't control every drawing independently. (sad
