### ISSUE TITLE
how can i get an instance of specific UnitType

### ISSUE THREAD

**Issue by K85** [ocraft/ocraft-s2client#50]
when i use the function debugCreateUnit()
`DebugInterface debugCreateUnit(UnitType var1, PointI var2, int var3, int var4);`
which needs a param `UnitType var1`.
However, I found some classes but none of them is suitable.
It seems I can only get UnitType from an exist unit instance by `unitInstance.getUnitType().`

besides, I found there is a class called `Units` which enums all the unit type names, but it's not a `UnitType`.

**Comment by ocraft** [comment]
https://github.com/ocraft/ocraft-s2client/blob/master/ocraft-s2client-bot/src/test/java/com/github/ocraft/s2client/bot/gateway/impl/DebugInterfaceImplIT.java - on there is an example for your case also. And you are wrong - `Units` implements `UnitType`, simply use `Units` enum when you need `UnitType`. Also, I encourage you to ask the questions on the discord (https://discordapp.com/invite/Emm5Ztz, #java channel), on there are many people that can help you, github is a place that is more suitable for reporting bugs or other issues.

**Comment by K85** [comment]
> https://github.com/ocraft/ocraft-s2client/blob/master/ocraft-s2client-bot/src/test/java/com/github/ocraft/s2client/bot/gateway/impl/DebugInterfaceImplIT.java - on there is an example for your case also. And you are wrong - `Units` implements `UnitType`, simply use `Units` enum when you need `UnitType`. Also, I encourage you to ask the questions on the discord (https://discordapp.com/invite/Emm5Ztz, #java channel), on there are many people that can help you, github is a place that is more suitable for reporting bugs or other issues.

thanks, i read the document again. you are right, it's my fault.
